"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [('resources', ['resources/apple.png', 'resources/block.jpg','resources/background.jpg','resources/bg_music_1.mp3',
                             'resources/crash.mp3','resources/ding.mp3'])]
OPTIONS = {
'packages': ['pygame'],
'iconfile':'MerriSnake.ico',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
